//APP
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_ASYNC = "FETCH_USER_ASYNC";
export const FIND_ROUTE_ASYNC = "FIND_ROUTE_ASYNC";
export const FIND_ROUTE = "FIND_ROUTE ";
export const START_FETCHING = "START_FETCHING";
export const STOP_FETCHING = "STOP_FETCHING";
export const SHOW_ERROR_FETCHING = "SHOW_ERROR_FETCHING";
export const HIDE_ERROR_FETCHING = "HIDE_ERROR_FETCHING";
export const HIDE_SUCCES_LABEL = "HIDE_SUCCES_LABEL";
export const SHOW_SUCCES_LABEL = "SHOW_SUCCES_LABEL";
export const ADD_TICKET = "ADD_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const SEND_TICKET = "SEND_TICKET";
export const RESET_TICKET = "RESET_TICKET";

//ADMIN
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_GET_ALL_USER = "ADMIN_GET_ALL_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_ASYNC = "DELETE_USER_ASYNC";
export const GET_ALL_ACTIVE_ROUTES = "GET_ALL_ACTIVE_ROUTES";
export const DELETE_ROUTE = "DELETE_ROUTE";
export const DELETE_ROUTE_ASYNC = "DELETE_ROUTE_ASYNC";
export const GET_ALL_TRANSPORT = "GET_ALL_TRANSPORT";
export const SET_NEW_ROUTE = "SET_NEW_ROUTE";
